name: simple_moments
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Bloc state management
  flutter_bloc: ^8.1.3

  # For internet
  dio: ^5.3.0

  # For service locator
  get_it: ^7.6.0

  # Internationalization, numbers etc
  intl: ^0.17.0

  #  # For international phone number
  intl_phone_number_input:
    git:
      url: https://github.com/Flutoms/intl_phone_number_input.git
      ref: develop

  # Change case
  change_case: ^1.1.0

  # Push notification
  firebase_messaging: ^14.4.1

  # To control showing notifications and create notification channels.
  flutter_local_notifications: ^13.0.0

  # Native splash
  flutter_native_splash: ^2.3.1

  # For Toast messages
  fluttertoast: ^8.2.2

  # For SVGs
  flutter_svg: ^2.0.7

  # Dear google fonts
  google_fonts: ^5.1.0

  # For pin
  pinput: ^2.3.0

  # For spacing
  gap: ^3.0.1

  # shimmer effect
  fade_shimmer: ^2.2.0

  # Load and Catch Image
  cached_network_image: ^3.2.3

  # Pager indicator
  smooth_page_indicator: ^1.1.0

  # Handle error
  dartz: ^0.10.1

  # For storage
  flutter_secure_storage: ^8.0.0

  # Fade in animations
  flutter_fadein: ^2.0.0

  # Handle permission
  permission_handler: ^11.0.1

  # Camera
  camera: ^0.10.5+5
  video_player:
  cached_video_player:

  # Flip counter
  animated_flip_counter: ^0.2.6

  # Google Auth
  google_sign_in: ^6.1.6

  # Firebase Auth
  firebase_auth: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/svg/
    - assets/images/png/
