// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xJQH_fhwiN7Chy_WXcx01OBH2UzK12I',
    appId: '1:753034776950:android:e20cb316852f2c2baf6a57',
    messagingSenderId: '753034776950',
    projectId: 'simplmet',
    storageBucket: 'simplmet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDvEwjHhgyN3SSvxYT9robiSvZM98eUCA',
    appId: '1:753034776950:ios:3f2f90f379d8b547af6a57',
    messagingSenderId: '753034776950',
    projectId: 'simplmet',
    storageBucket: 'simplmet.appspot.com',
    androidClientId: '753034776950-ervbitv010vf5r36f58ss3lgd7ec20j9.apps.googleusercontent.com',
    iosClientId: '753034776950-oaermto4vgkg26i9qs0e4ha07orujooh.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleMoments',
  );
}
